@startuml

left to right direction
:Agente:
usecase "Evaluar solicitud de credito" as CU1
:Agente: -- CU1
usecase "Solicitar informacion adicional al cliente" as CU2

CU1 ..  CU2 :<<extend>>




@enduml