@startuml
left to right direction

usecase "Introducir pedido" as CU1
usecase "Cancelar pedido" as CU2
usecase "Obtener estado del pedido" as CU3
usecase "Buscar pedido" as CU5
usecase "Alta cliente" as CU6
usecase "Buscar cliente" as CU9
usecase "Pago efectivo" as CU10
usecase "Pago tarjeta" as CU11

:Empleado: -- CU1
:Empleado: -- CU2
:Empleado: -- CU3
:Empleado: -- CU5
:Empleado: -- CU6

CU1 .. CU6 : <<extend>>
CU1 .. CU9 : <<incluye>>
CU2 .. CU5 : <<incluye>>
CU3 .. CU5 : <<incluye>>
CU10 .. CU1 : <<extend>>
CU11 .. CU1 : <<extend>>


@enduml